/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package f;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;

public class AppTest {
    fracciones f, f2;
    @Before public void setUp(){
        f = new fracciones(2,4);
        f2 = new fracciones(2, 3);
    }

    @Test public void Simplificar() {
       f.Simplifica();
       assertEquals(1, f.getNumerador());
       assertEquals(2, f.getDenominador());
    }

    @Test
    public void Imprime() {
        assertTrue(f.Imprime().equals("1/2"));
    }

    @Test
    public void Suma() {
        fracciones res = new fracciones();
        res = res.Suma(f, f2);
        assertTrue(res.getNumerador() == 7 && res.getDenominador() == 6);
    }

    @Test
    public void Multiplicar() {
        fracciones res = new fracciones();
        res = res.Multiplicar(f, f2);
        assertTrue(res.getNumerador() == 1 && res.getDenominador() == 3);
    }
    @Test 
     public void SumaMat()
     {
        matFrac Matriz3 = new matFrac();
        matFrac Respuesta = new matFrac("Prueba.txt");
        Matriz3.Suma("Matriz1.txt", "Matriz2.txt", "Matriz3.txt");
        for(int i =0; i<Respuesta.getFilas(); i++)
        {
            for(int j = 0; j<Respuesta.getColumnas(); j++)
            {
             assertTrue(Matriz3.getFraccion(i,j).getDenominador() == Respuesta.getFraccion(i,j).getDenominador());
             assertTrue(Matriz3.getFraccion(i,j).getNumerador() == Respuesta.getFraccion(i,j).getNumerador());
            }
        }
     }
}
